pull_request_rules:
  - name: automatic merge for master when CI passes and 1 reviews
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=check_pr
      - base=master
    actions:
      merge:
        method: merge
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=check_pr
    actions:
      merge:
        method: merge